"""add sort_order to niches

Revision ID: f107980d03ef
Revises: 89d6557fae42
Create Date: 2026-03-20 06:55:22.308699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f107980d03ef'
down_revision: Union[str, Sequence[str], None] = '89d6557fae42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niches', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'sort_order')
    # ### end Alembic commands ###
